

SELECT FLAVOR FROM(
SELECT FH.FLAVOR, (FH.TOTAL_ORDER + J.TOTAL) AS GOOD
FROM FIRST_HALF FH INNER JOIN(SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
FROM JULY
GROUP BY FLAVOR) J
ON FH.FLAVOR = J.FLAVOR
ORDER BY GOOD DESC
) WHERE ROWNUM <=3

만약 상위3개가 아니라 하위3개면 ORDER BY 조건은 바꾸면된다
